# Generated by Django 4.1.5 on 2023-08-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-id",)},
        ),
    ]
