# Generated by Django 4.1.5 on 2023-08-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="address_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="address_ru",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="address_uz",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_uz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uz",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
